# Generated by Django 4.2 on 2024-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
