# Generated by Django 4.2 on 2024-09-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_publications_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'permissions': [('can_publish_incident', 'Can publish incidents')], 'verbose_name': 'Incidents', 'verbose_name_plural': 'Incident'},
        ),
    ]
