# Generated by Django 4.2 on 2025-04-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_incidents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
