# Generated by Django 4.2 on 2025-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_publications_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='category',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 2}, null=True, related_name='Violence_category', to='web.options'),
        ),
    ]
