# Generated by Django 4.2 on 2025-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_incidents_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='date_publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
