# Generated by Django 4.2 on 2025-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_publications_date_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violence',
            options={'ordering': ['incident', 'sequence'], 'verbose_name': 'Violences', 'verbose_name_plural': 'Violence'},
        ),
        migrations.AddField(
            model_name='violence',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='Sequence number for multiple violence forms per incident (1, 2, 3, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='violence',
            unique_together={('incident', 'sequence')},
        ),
    ]
