# Generated by Django 4.2 on 2026-05-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_add_violence_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-date_publish', '-created_at'], 'verbose_name': 'Publications', 'verbose_name_plural': 'Publications'},
        ),
    ]
